# Copyright 2020 Hewlett Packard Enterprise Development LP

# Dockerfile for testing base HMS TRS App API code.

FROM cray/hms-trs-app-api-build-base

# Run any tests that might be present.
RUN set -ex \
    && go test -v $GOPATH/src/stash.us.cray.com/HMS/hms-trs-app-api/pkg/./...
