# Copyright 2020 Hewlett Packard Enterprise Development LP

# Dockerfile for running testing coverage on base HMS TRS App API code.

FROM cray/hms-trs-app-api-build-base

# Run coverage.
RUN set -ex \
    && go test -cover -v stash.us.cray.com/HMS/hms-trs-app-api/pkg/./...
